name: stundenplan
description: Stundenplan app für das HAG

publish_to: 'none'

version: 1.4.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  html: ^0.14.0+3
  google_fonts: ^1.1.0
  intl:  ^0.16.1
  tuple: ^1.0.3
  shared_preferences: ^0.5.10
  flutter_launcher_icons: ^0.7.3
  pull_to_refresh: ^1.6.1
  package_info: ^0.4.0+16
  yaml: ^2.2.1
  connectivity: ^0.4.9+2
  url_launcher: ^5.5.2
  time_ago_provider: ^2.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"

dev_dependencies:
  lint: ^1.3.0
  pedantic: ^1.0.0
  test : ^1.15.4
  mockito : ^4.1.1

flutter:
  uses-material-design: true
