name: stundenplan
description: Stundenplan app für das HAG

publish_to: 'none'

version: 1.4.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  html: ^0.15.0
  google_fonts: ^2.0.0
  intl: ^0.17.0
  tuple: ^2.0.0
  shared_preferences: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  pull_to_refresh: ^1.6.4
  package_info: ^2.0.0
  yaml: ^3.1.0
  connectivity: ^3.0.3
  url_launcher: ^6.0.3
  time_ago_provider: ^4.0.0
  flutter_colorpicker: ^0.4.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.8

flutter:
  uses-material-design: true
